version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    container_name: api
    hostname: api
    networks:
      default:
        aliases:
          - api.local
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    networks:
      default:
        aliases:
          - postgres.local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   restart: always
  #   container_name: redis
  #   hostname: redis
  #   networks:
  #     default:
  #       aliases:
  #         - redis.local
  #   ports:
  #     - "6379:6379"

networks:
  default:

volumes:
  api:
  postgres:
